
name: Deploy Blog

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:      
      - uses: actions/checkout@v2

      - name: Build Blog Post
        run: |
          pandoc --standalone \
            --template ./docs/gan-blog/templates/template.html \
            ./docs/gan-blog/markdown/trained-a-gan.md \
            -o ./docs/gan-blog/trained-a-gan.html

      - name: Build Training Notes
        run: |
          pandoc --standalone \
            --template ./docs/gan-blog/templates/template.html \
            ./docs/gan-blog/markdown/gan-training-notes.md \
            -o ./docs/gan-blog/gan-training-notes.html

      - name: Build Treat
        run: |
          pandoc --standalone \
            --template ./docs/gan-blog/templates/template.html \
            ./docs/gan-blog/markdown/gallery.md \
            -o ./docs/gan-blog/gallery.html
         
      - name: Deploy Blog Section
        run: |
          aws s3 sync ./docs/gan-blog/ s3://dmw2151.com/ --region us-east-1
